
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('books').del()
    .then(function () {
      // Inserts seed entries
      return knex('books').insert([
        {title: "Red Sister", description: "At the Convent of Sweet Mercy young girls are raised to be killers. In a few the old bloods show, gifting talents rarely seen since the tribes beached their ships on Abeth. Sweet Mercy hones its novices’ skills to deadly effect: it takes ten years to educate a Red Sister in the ways of blade and fist.",author: 'Mark Lawrence', image: 'https://images.gr-assets.com/books/1481038440l/25895524.jpg', genre: 'Fantasy'},
        {title: "Throne of Glass", description: "After serving out a year of hard labor in the salt mines of Endovier for her crimes, 18-year-old assassin Celaena Sardothien is dragged before the Crown Prince. Prince Dorian offers her her freedom on one condition: she must act as his champion in a competition to find a new royal assassin.",author: 'Sara J Mass', image: 'https://images.gr-assets.com/books/1495278054l/7896527.jpg', genre: 'Fantasy'},
        {title: "Defy the Stars", description: "Noemi Vidal is seventeen years old and sworn to protect her planet, Genesis. She’s willing to risk anything—including her own life. To their enemies on Earth, she’s a rebel.",author: 'Claudia Gray', image: 'https://images.gr-assets.com/books/1484967166l/31423196.jpg', genre: 'Fantasy'},
        {title: "Borne", description: "In a ruined, nameless city of the future, a woman named Rachel, who makes her living as a scavenger, finds a creature she names “Borne” entangled in the fur of Mord, a gigantic, despotic bear. Mord once prowled the corridors of the biotech organization known as the Company, which lies at the outskirts of the city, until he was experimented on, grew large, learned to fly and broke free. Driven insane by his torture at the Company, Mord terrorizes the city even as he provides sustenance for scavengers like Rachel." ,author: 'Jeff VanderMerr', image: 'https://images.gr-assets.com/books/1480788387l/28225843.jpg', genre: 'Fantasy'},
        {title:"IT", description: "To the children, the town was their whole world. To the adults, knowing better, Derry, Maine was just their home town: familiar, well-ordered for the most part. A good place to live.", author: 'Stephen King', image: 'https://images.gr-assets.com/books/1334416842l/830502.jpg', genre: 'Horror'},
        {title:"World War Z ", description: "The Zombie War came unthinkably close to eradicating humanity. Max Brooks, driven by the urgency of preserving the acid-etched first-hand experiences of the survivors from those apocalyptic years, traveled across the United States of America and throughout the world, from decimated cities that once teemed with upwards of thirty million souls to the most remote and inhospitable areas of the planet. He recorded the testimony of men, women, and sometimes children who came face-to-face with the living, or at least the undead, hell of that dreadful time. World War Z is the result. Never before have we had access to a document that so powerfully conveys the depth of fear and horror, and also the ineradicable spirit of resistance, that gripped human society through the plague years.", author: 'Max Brooks', image: 'https://images.gr-assets.com/books/1386328204l/8908.jpg', genre: 'Horror'},
        {title:"Hollow City", description: "Miss Peregrine’s Home for Peculiar Children was the surprise best seller of 2011—an unprecedented mix of YA fantasy and vintage photography that enthralled readers and critics alike. Publishers Weekly called it “an enjoyable, eccentric read, distinguished by well-developed characters, a believable Welsh setting, and some very creepy monsters.”", author: 'Ransom Riggs', image: 'https://images.gr-assets.com/books/1429175859l/23164983.jpg', genre: 'Fantasy'},
        {title:"The Beast Is an Animal", description: "A girl with a secret talent must save her village from the encroaching darkness in this haunting and deeply satisfying tale. Alys was seven when the soul eaters came to her village.", author: 'Peternelle van Arsdale', image: 'https://images.gr-assets.com/books/1464054363l/29522966.jpg', genre: 'Horror'},
        {title:"See What I Have Done", description: "In this riveting debut novel, See What I Have Done, Sarah Schmidt recasts one of the most fascinating murder cases of all time into an intimate story of a volatile household and a family devoid of love.", author: 'Sarah Schimdt', image: 'https://images.gr-assets.com/books/1481137541l/32508637.jpg', genre: 'Horror'},
        {title:"The Little Prince", description: "Moral allegory and spiritual autobiography, The Little Prince is the most translated book in the French language. With a timeless charm it tells the story of a little boy who leaves the safety of his own tiny planet to travel the universe, learning the vagaries of adult behaviour through a series of extraordinary encounters. His personal odyssey culminates in a voyage to Earth and further adventures.", author: 'Antoine de Saint-Exupery', image: 'https://images.gr-assets.com/books/1367545443l/157993.jpg', genre: 'Fantasy'},
        {title:"1984", description: "The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever. 1984 is still the great modern classic of 'negative utopia' -a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny the novel's hold on the imaginations of whole generations, or the power of its admonitions -a power that seems to grow, not lessen, with the passage of time.", author: 'George Orwell', image: 'https://images.gr-assets.com/books/1348990566l/5470.jpg', genre: 'Horror'},
        {title:"The Lighthouse Keeper: A Caotionary Tale", description: "A hapless children's picture book tale of a lighthouse keeper who, well, just isn't very good at his job... or is he?  Will the little boat get a happy ending and be guided to safety by the beam of the lighthouse or will it go down in a watery whirl!  A children's picture book tale which will appeal to both adults and children with it's quirky humour!", author: 'Zoe Sadler', image: 'https://images.gr-assets.com/books/1492517504l/23058576.jpg', genre: 'Horror'},
        {title:"Startup", description: "From veteran online journalist and BuzzFeed writer Doree Shafrir comes a hilarious debut novel that proves there are some dilemmas that no app can solve.  Mack McAllister has a $600 million dollar idea. His mindfulness app, TakeOff, is already the hottest thing in tech and he's about to launch a new and improved version that promises to bring investors running and may turn his brainchild into a $1 billion dollar business--in startup parlance, an elusive unicorn. ", author: 'Doree Shafrir', image: 'https://images.gr-assets.com/books/1473240187l/31423188.jpg', genre: 'Fantasy'},
        {title:"Never Summer", description: "In the mid-19th century, the itinerant Vlad D’Agostino arrives in New York City after a long stay in Japan, bringing with him a samurai mask and a terminal case of tuberculosis. In Manhattan, he learns of an innovative doctor who claims to have found a treatment for the disease using alpine air, but Vlad will have to travel to the physician’s clinic in the Rocky Mountains, in a place known as Never Summer...On his quest to save himself and prolong his life, he inadvertently makes discoveries about his traumatic past—and about how to live more fully in the present...Vlad is a thoughtful hero, and Blaine seems just as interested in evoking Herman Melville’s work as he is Zane Grey’s. Adventure fans of all stripes will find something compelling in the tragic, mysterious protagonist. An original, philosophically minded Western adventure. -Kirkus Reviews", author: 'Tim Blaine', image: 'https://images.gr-assets.com/books/1482337455l/33527266.jpg', genre: 'Fantasy'},
        {title:"The Hobbit", description: "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort. Written for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent. The text in this 372-page paperback edition is based on that first published in Great Britain by Collins Modern Classics (1998), and includes a note on the text by Douglas A. Anderson (2001). Unforgettable!", author: 'J.R.R. Tolkien', image: 'https://images.gr-assets.com/books/1372847500l/5907.jpg', genre: 'Fantasy'},
        {title:"Harry Potter and the Goblet of Fire ", description: "Harry Potter is midway through both his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event that supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards. And in his case, different can be deadly.", author: 'J.K. Rowling', image: 'https://images.gr-assets.com/books/1361482611l/6.jpg', genre: 'Fantasy'}
      ]);
    });
};
